name: grocery_admin_panel
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  iconly: ^1.0.1
  dotted_border: ^2.0.0+2
  image_picker: ^0.8.5
  uuid: ^3.0.6
  fluttertoast: ^8.0.9
  internet_connection_checker:
  connectivity_plus: ^2.3.5
  url_launcher: ^6.0.20
  # Firebase
  firebase_core: ^1.15.0
  cloud_firestore: ^3.1.13
  firebase_storage: ^10.2.14
  firebase: ^9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  change_app_package_name: ^1.1.0
#flutter pub run change_app_package_name:main com.new.package.name
  flutter_app_name: ^0.1.1
#flutter pub run flutter_app_name
  flutter_launcher_icons: ^0.9.3
#flutter pub run flutter_launcher_icons:main

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo2.png"


flutter_app_name:
  name: "Admin Ghor Chai"


flutter:
  uses-material-design: true

  assets:
    - assets/images/ghor-chai-logo.png
    - assets/images/internet.png
    - assets/images/warning-sign.png
    - assets/images/
